project:
  render:
    - tutorial-predictive.qmd
title: 'Tutorial 9: Predictive Analytics for Workforce Planning - Solutions'
format:
  html:
    output-file: "tutorial-9-solutions"
    output-ext:  "html"
