project:
  render:
    - tutorial.qmd
title: 'Tutorial 11: Predictive Analytics for Workforce Planning - Teaching Guide'
format:
  html:
    output-file: "tutorial-r-teaching-guide"
    output-ext:  "html"
